#define COLUMNS_COUNT 13

#define COLUMN_TIME 0
#define COLUMN_DEAL 1
#define COLUMN_SYMBOL 2
#define COLUMN_TYPE  3
#define COLUMN_DIRECTION 4
#define COLUMN_VOLUME 5
#define COLUMN_PRICE  6
#define COLUMN_ORDER  7
#define COLUMN_COMISSION 8
#define COLUMN_SWAP 9
#define COLUMN_PROFIT 10
#define COLUMN_BALANCE 11
#define COLUMN_COMMENT 12
